#36add logging
wbaku/ContractAnalyzer pull request #39
Opened 2021-05-26 13:18 UTC by Anastasiya4567

2021-05-27 09:36 UTC, jkiljanski commented
Czy dałoby radę jeszcze to pożenić z logbackiem? Nie chciałbym utrzymywać wielu plików konfiguracyjnym pod loggery

2021-05-27 09:38 UTC, jkiljanski requested changes
jak w komentarzu - jeszcze integracja z logbackiem jest potrzebna. Jakbyś mogła też dodać pliczek z konfiguracją log4j2

2021-05-31 11:20 UTC, Anastasiya4567 commented
Nowa wersja już jest

2021-05-31 11:25 UTC, jkiljanski approved these changes

2021-05-31 11:25 UTC, merged