The end of refactor Java->Vavr
wbaku/ContractAnalyzer pull request #53
Opened 2021-07-16 13:01 UTC by Anastasiya4567

2021-07-20 14:08 UTC, wbaku commented on src/main/java/com/sciamus/contractanalyzer/domain/reporting/idGenerator/AggregatedReportIdGenerator.java
> +        nextID = Long.toString(aggregatedChecksRepository.count() + 1);
przez konwencję: id w MongoDB zawsze jest Stringiem stąd `1+""`

2021-07-22 16:00 UTC, jkiljanski requested changes

2021-07-22 16:00 UTC, jkiljanski commented on src/main/java/com/sciamus/contractanalyzer/misc/conf/FeignClientsConfig.java
> +//            Match(keycloakSecurityContext).of(
## warn

leftovers

2021-07-23 09:30 UTC, Anastasiya4567 commented on src/main/java/com/sciamus/contractanalyzer/domain/reporting/aggregatedChecks/AggregatedChecksService.java
> +    public java.util.List<AggregatedChecksReport> getAggregatedChecksReports() {
findAll() zwraca wyłącznie listy javowe. można ją przekorwertową na vavrową, a w kontrolerze znowu na javową, ale jaki sens? dlatego tak zrobiłam

2021-07-26 12:34 UTC, merged